<a href="https://colab.research.google.com/github/Amit-Padye/CNN/blob/main/CNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 pip install tensorflow numpy mnist

In [24]:
import numpy as np
import mnist
from tensorflow import keras

# The first time you run this might be a bit slow, since the
# mnist package has to download and cache the data.
train_images = mnist.train_images()
train_labels = mnist.train_labels()

print(train_images.shape) # (60000, 28, 28)
print(train_labels.shape) # (60000,)

(60000, 28, 28)
(60000,)


In [28]:
import numpy as np
import mnist

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5



In [13]:
train_images

array([[[-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        ...,
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5]],

       [[-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        ...,
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5]],

       [[-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        ...,
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5]],

       ...,

       [[-0.5, -0.5, -0.

In [29]:
# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

print(train_images.shape) # (60000, 28, 28, 1)
print(test_images.shape)  # (10000, 28, 28, 1)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
from tensorflow.keras.models import Sequential

# WIP
model = Sequential([
  # layers...
])

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [32]:
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

num_filters = 8
filter_size = 3
pool_size = 2

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

In [33]:
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [34]:
import mnist

train_labels = mnist.train_labels()
print(train_labels[0]) # 5

5


In [35]:
from tensorflow.keras.utils import to_categorical

model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 18s 9ms/step - loss: 0.3500 - accuracy: 0.8985 - val_loss: 0.2125 - val_accuracy: 0.9368
Epoch 2/3
1875/1875 [==============================] - 17s 9ms/step - loss: 0.1922 - accuracy: 0.9439 - val_loss: 0.1502 - val_accuracy: 0.9550
Epoch 3/3
1875/1875 [==============================] - 17s 9ms/step - loss: 0.1416 - accuracy: 0.9593 - val_loss: 0.1255 - val_accuracy: 0.9628


In [3]:
import numpy as np
import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from tensorflow.keras.utils import to_categorical

train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

num_filters = 8
filter_size = 3
pool_size = 2

# Build the model.
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

# Compile the model.
model.compile(
  'adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

# Train the model.
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=3,
  validation_data=(test_images, to_categorical(test_labels)),
)

Epoch 1/3
1875/1875 [==============================] - 21s 4ms/step - loss: 0.3579 - accuracy: 0.8976 - val_loss: 0.2024 - val_accuracy: 0.9432
Epoch 2/3
1875/1875 [==============================] - 8s 5ms/step - loss: 0.1744 - accuracy: 0.9504 - val_loss: 0.1411 - val_accuracy: 0.9594
Epoch 3/3
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1274 - accuracy: 0.9639 - val_loss: 0.1171 - val_accuracy: 0.9633


In [6]:
model.save_weights('cnn.h5')

In [7]:
# Load the model's saved weights.
model.load_weights('cnn.h5')

In [8]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]


In [ ]:
predictions

#Network Depth
What happens if we add or remove Convolutional layers? How does that affect training and/or the model’s final performance?

In [10]:
model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  Conv2D(num_filters, filter_size),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

##Dropout

In [11]:
from tensorflow.keras.layers import Dropout

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Dropout(0.5),
  Flatten(),
  Dense(10, activation='softmax'),
])

##Fully-connected Layers

In [12]:
from tensorflow.keras.layers import Dense

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])


In [13]:
# These can be changed, too!
num_filters = 8
filter_size = 3

model = Sequential([
  # See https://keras.io/layers/convolutional/#conv2d for more info.
  Conv2D(
    num_filters,
    filter_size,
    input_shape=(28, 28, 1),
    strides=2,
    padding='same',
    activation='relu',
  ),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])